config/routes.rb
MusicApp::Application.routes.draw do
  resources :users, only: [:create, :new, :show]

  resource :session, only: [:create, :new, :destroy]

  resources :bands

  resources :albums, only: [:new, :create, :edit, :show,
    :update, :destroy]

  resources :tracks, only: [:new, :create, :edit, :show,
    :update, :destroy]

  resources :notes, only: [:new, :create, :edit, :show,
    :update, :destroy]

  root to: "sessions#new"

end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id          :integer          not null, primary key
#  track_id    :integer          not null
#  user_id     :integer          not null
#  created_at  :datetime
#  updated_at  :datetime
#  track_notes :text
#

class Note < ActiveRecord::Base
  belongs_to(
    :track
  )

  belongs_to(
    :user
  )

  validates :user_id, :track_id, :track_notes, presence: true


end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def new
    @note = Note.new
    render :new
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id

    if @note.save
      redirect_to track_url(Track.find(@note.track_id))
    else
      flash.now[:errors] = @note.errors.full_messages
      render :new
    end
  end

  def show
    @note = Note.find(params[:id])
    render :show
  end

  def edit
    @note = Note.find(params[:id])
    render :edit
  end

  def update
    @note = Note.find(params[:id])

    if @note.update(note_params)
      redirect_to note_url(@note)
    else
      flash.now[:errors] = @note.errors.full_messages
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])

    render text: "Not owner of note!" if current_user.id != @note.user_id

    if @note.destroy
      flash[:errors] = ["Note deleted"]
      redirect_to track_url(Track.find(@note.track_id))
    else
      flash.now[:errors] = ["No note exists"]
      redirect_to track_url(Track.find(@note.track_id))
    end
  end

  private
  def note_params
    params.require(:notes).permit(:track_notes, :track_id)
  end

end

app/views/notes/_form.html.erb
<h3>Create Note</h3>

  <form action="<%= notes_url %>" method="post">
    <input type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token  %>">

      <input type="hidden"
        name="notes[track_id]"
        value="<%= @track.id  %>">

    <label for="notes_track_notes">Notes
      <br>
      <textarea name="notes[track_notes]" id="notes_track_notes"><%=  %></textarea>
    </label><br><br>

    <button>Create Note</button>

  </form>

app/views/notes/show.html.erb
<h1>Track: <%= @track.track_title %></h1>

  <h2>Artist: <%= @track.album.band.name %></h2>

  <h2>Album: <%= @track.album.title %></h2>

  <h2>Style: <%= @track.song_type.capitalize %></h2>

  <label for="track_lyrics">Lyrics
    <br>
    <br>
    <text name="track[lyrics]" id="track_lyrics"><%= @track.lyrics == "" ? "No lyrics available" : @track.lyrics %></textarea>
  </label><br><br>

  <%= button_to "Edit Track", edit_track_url(@track), method: :get %>
  <form action="<%= track_url %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <%= button_to "Delete Track", track_url(@track), method: :post %>
  </form>
  <%= button_to "Back to Album", album_url(@track.album.id), method: :get %>