config/routes.rb
MusicApp::Application.routes.draw do
  resources :users, only: [:create, :new, :show]

  resource :session, only: [:create, :new, :destroy]

  resources :bands

  resources :albums, only: [:new, :create, :edit, :show,
    :update, :destroy]

  resources :tracks, only: [:new, :create, :edit, :show,
    :update, :destroy]

  resources :notes, only: [:new, :create, :edit, :show,
    :update, :destroy]

  root to: "sessions#new"

end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id          :integer          not null, primary key
#  album_id    :integer          not null
#  song_type   :string(255)      not null
#  lyrics      :text
#  created_at  :datetime
#  updated_at  :datetime
#  track_title :string(255)
#

class Track < ActiveRecord::Base
  SONG_TYPES = %w{ bonus regular }

  belongs_to(
    :album,
    class_name: 'Album',
    foreign_key: :album_id,
    primary_key: :id
  )

  has_many(
    :notes
  )
  validates :album_id, :song_type, :track_title, presence: true
  validates :song_type, inclusion: { in: SONG_TYPES }
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def new
    if !params[:track].nil?
      @track = Track.new(album_id: params[:track][:album_id])
    else
      @track = Track.new
    end

    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])

    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])

    if @track.destroy
      flash[:errors] = ["Track deleted"]
      redirect_to album_url(@track.album_id)
    else
      flash.now[:errors] = ["No Track exists"]
      redirect_to album_url(@track.album_id)
    end
  end

  private
  def track_params
    params.require(:track).permit(:album_id, :song_type,
      :lyrics, :track_title)
  end

end

app/views/tracks/edit.html.erb
<h1>Update Track</h1>

  <form action="<%= track_url(@track) %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token  %>">

    <label for="track_album_id">Album
      <select name="track[album_id]" id="track_album_id">
        <option value=""></option>
        <% Album.all.each do |album| %>
          <option value="<%= album.id %>"
            <%= "selected" if album.id == @track.album_id %>>
            <%= album.title %></option>
        <% end %>
      </select>
    </label><br><br>


    <label for="track_song_type">Type
        <% Track::SONG_TYPES.each do |type| %>
          <input type="radio" name="track[song_type]"
            id="track_song_type" value="<%= type %>"
            <%= "checked" if @track.song_type == type %>>
          <label for="track_song_type"><%= type %></label>
        <% end %>
    </label><br><br>

    <label for="track_track_title">Title
      <input type="text"
        name="track[track_title]"
        id="track_track_title"
        value="<%= @track.track_title %>">
    </label><br><br>

    <label for="track_lyrics">Lyrics
      <br>
      <textarea name="track[lyrics]" id="track_lyrics"><%= @track.lyrics %></textarea>
    </label><br><br>

    <button>Update Track</button>

  </form>

app/views/tracks/new.html.erb
<h1>Create Track</h1>

  <form action="<%= tracks_url %>" method="post">
    <input type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token  %>">

    <label for="track_album_id">Album
      <select name="track[album_id]" id="track_album_id">
        <option value=""></option>
        <% Album.all.each do |album| %>
          <option value="<%= album.id %>"
            <%= "selected" if album.id == @track.album_id %>>
            <%= album.title %></option>
        <% end %>
      </select>
    </label><br><br>


    <label for="track_song_type">Type
        <% Track::SONG_TYPES.each do |type| %>
          <input type="radio" name="track[song_type]"
            id="track_song_type" value="<%= type %>"
            <%= "checked" if @track.song_type == type %>>
          <label for="track_song_type"><%= type %></label>
        <% end %>
    </label><br><br>

    <label for="track_track_title">Title
      <input type="text"
        name="track[track_title]"
        id="track_track_title"
        value="<%= @track.track_title %>">
    </label><br><br>

    <label for="track_lyrics">Lyrics
      <br>
      <textarea name="track[lyrics]" id="track_lyrics"><%= @track.lyrics %></textarea>
    </label><br><br>

    <button>Create Track</button>

  </form>

app/views/tracks/show.html.erb
<h1>Track: <%= @track.track_title %></h1>

  <h2>Artist: <%= @track.album.band.name %></h2>

  <h2>Album: <%= @track.album.title %></h2>

  <h2>Style: <%= @track.song_type.capitalize %></h2>

  <label for="track_lyrics">Lyrics</label>
  <% if @track.lyrics == "" %>
    <p><%="No lyrics available"%></p>
  <%else%>
    <% ugly_lyrics(@track.lyrics).each do |line| %>
      <p><%= line %></p>
    <%end%>
  <%end%>

  <%= button_to "Edit Track", edit_track_url(@track), method: :get %>
  <form action="<%= track_url %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <%= button_to "Delete Track", track_url(@track), method: :post %>
  </form>
  <%= button_to "Back to Album", album_url(@track.album.id), method: :get %>

<br>

<h3>Notes</h3>

<table>
  <tr>
    <th>User</th>
    <th>Note</th>
    <th>Delete</th>
  </tr>

  <% @track.notes.each do |note| %>
    <tr>
      <td><%= User.find(note.user_id).email %></td>

      <td><%= note.track_notes %></td>

      <td>
        <% if note.user_id == current_user.id %>
          <form action="<%= note_url(note) %>" method="post">
          <input type="hidden" name="_method" value="delete">
          <%= button_to "Delete Note", note_url(note), method: :post %>
          </form>
        <% end %>
      </td>


    </tr>
  <% end %>
</table>

<%= render "notes/form.html.erb" %>