config/routes.rb
MusicApp::Application.routes.draw do
  resources :users, only: [:create, :new, :show]

  resource :session, only: [:create, :new, :destroy]

  resources :bands

  resources :albums, only: [:new, :create, :edit, :show,
    :update, :destroy]

  resources :tracks, only: [:new, :create, :edit, :show,
    :update, :destroy]

  resources :notes, only: [:new, :create, :edit, :show,
    :update, :destroy]

  root to: "sessions#new"

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  style_type :string(255)      not null
#  title      :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Album < ActiveRecord::Base
  STYLE_TYPES = %w{ live studio }

  belongs_to(
    :band,
    class_name: 'Band',
    foreign_key: :band_id,
    primary_key: :id
  )

  has_many(
    :tracks,
    class_name: 'Track',
    foreign_key: :album_id,
    primary_key: :id,
    dependent: :destroy
  )

  validates :band_id, :style_type, :title, presence: true
  validates :style_type, inclusion: { in: STYLE_TYPES }
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    if !params[:album].nil?
      @album = Album.new(band_id: params[:album][:band_id])
    else
      @album = Album.new
    end

    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])

    if @album.destroy
      flash[:errors] = ["Album deleted"]
      redirect_to user_url(current_user.id)
    else
      flash.now[:errors] = ["No album exists"]
      redirect_to user_url(current_user.id)
    end
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :style_type,
      :title,)
  end

end

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

  <form action="<%= album_url(@album) %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token  %>">

    <label for="album_band_id">Band
      <select name="album[band_id]" id="album_band_id">
        <option value=""></option>
        <% Band.all.each do |band| %>
          <option value="<%= band.id %>" <%= "selected" if band.id == @album.band_id %>>
            <%= band.name %></option>
        <% end %>
      </select>
    </label><br><br>

    <label for="album_style_type">Type
        <% Album::STYLE_TYPES.each do |type| %>
          <input type="radio" name="album[style_type]"
            id="album_style_type" value="<%= type %>">
          <label for="album_style_type"><%= type %></label>
        <% end %>
    </label><br><br>

    <label for="album_title">Title
      <input type="text"
        name="album[title]"
        id="album_title"
        value="<%= @album.title %>">
    </label><br><br>

    <button>Update Album</button>

  </form>

app/views/albums/new.html.erb
<h1>Create Album</h1>

  <form action="<%= albums_url %>" method="post">
    <input type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token  %>">

    <label for="album_band_id">Band
      <select name="album[band_id]" id="album_band_id">
        <option value=""></option>
        <% Band.all.each do |band| %>
          <option value="<%= band.id %>"
            <%= "selected" if band.id == @album.band_id %>>
            <%= band.name %></option>
        <% end %>
      </select>
    </label><br><br>

    <label for="album_style_type">Type
        <% Album::STYLE_TYPES.each do |type| %>
          <input type="radio" name="album[style_type]"
            id="album_style_type" value="<%= type %>">
          <label for="album_style_type"><%= type %></label>
        <% end %>
    </label><br><br>

    <label for="album_title">Title
      <input type="text"
        name="album[title]"
        id="album_title"
        value="<%= @album.title %>">
    </label><br><br>

    <button>Create Album</button>

  </form>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
  <h2><%= @album.band.name %></h2>
  <h2>Style: <%= @album.style_type %></h2>

  <%= button_to "Edit Album", edit_album_url(@album), method: :get %>
  <form action="<%= album_url %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <%= button_to "Delete Album", album_url(@album), method: :post %>
  </form><br>

  <form action="<%= new_track_url %>" method="get">
    <input type="hidden" name="track[album_id]" value="<%= @album.id %>">
  <button>Add Track</button>
  </form>

  <h3>Tracks</h3>

  <table>
    <tr>
      <th>Title</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>

    <% @album.tracks.each do |track| %>
      <tr>
        <td><a href="<%= track_url(track) %>"><%= track.track_title %></a></td>

        <td><%= button_to "Edit Track", edit_track_url(track.id), method: :get %></td>

        <td>
          <form action="<%= track_url(track) %>" method="post">
            <input type="hidden" name="_method" value="delete">
            <%= button_to "Delete Track", track_url(track), method: :post %>
          </form>
        </td>

      </tr>
    <% end %>
  </table>