config/routes.rb
MusicApp::Application.routes.draw do
  resources :users, only: [:create, :new, :show]

  resource :session, only: [:create, :new, :destroy]

  resources :bands

  resources :albums, only: [:new, :create, :edit, :show,
    :update, :destroy]

  resources :tracks, only: [:new, :create, :edit, :show,
    :update, :destroy]

  resources :notes, only: [:new, :create, :edit, :show,
    :update, :destroy]

  root to: "sessions#new"

end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Band < ActiveRecord::Base
  has_many(
    :albums,
    class_name: 'Album',
    foreign_key: :band_id,
    primary_key: :id,
    dependent: :destroy
  )

  validates :name, presence: true, uniqueness: true

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])

    if @band.destroy
      flash[:errors] = ["Band deleted"]
      redirect_to user_url(current_user.id)
    else
      flash.now[:errors] = ["No band exists"]
      redirect_to user_url(current_user.id)
    end
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token  %>">

  <label for="band_name">Name:
    <input type="text"
      name="band[name]"
      id="band_name"
      value="<%= @band.name %>">
  </label><br><br>

  <button>Submit</button>

</form>

app/views/bands/index.html.erb
<h1>Bands
  <%= button_to "Create Band", new_band_url, method: :get %>
</h1>

<table>
  <% @bands.each do |band| %>
    <tr>
      <td><a href="<%= band_url(band) %>"><%= band.name %></a></td>

      <td><%= button_to "Edit Band", edit_band_url(band.id), method: :get %></td>

      <td>
        <form action="<%= band_url(band) %>" method="post">
          <input type="hidden" name="_method" value="delete">
          <%= button_to "Delete Band", band_url(band), method: :post %>
        </form>
      </td>

      <td>
        <form action="<%= new_album_url %>" method="get">
          <input type="hidden" name="album[band_id]" value="<%= band.id %>">
        <button>Add Album</button>
        </form>
      </td>

    </tr>
  <% end %>
</table>

app/views/bands/new.html.erb
<h1>Create Band</h1>

<form action="<%= bands_url %>" method="post">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token  %>">

  <label for="band_name">Name:
    <input type="text"
      name="band[name]"
      id="band_name"
      value="<%= @band.name %>">
  </label><br><br>

  <button>Create Band</button>

</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
  <%= button_to "Edit Band", edit_band_url(@band), method: :get %>
  <form action="<%= band_url %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <%= button_to "Delete Band", band_url(@band), method: :post %>
  </form><br>

  <form action="<%= new_album_url %>" method="get">
    <input type="hidden" name="album[band_id]" value="<%= @band.id %>">
  <button>Add Album</button>
  </form><br>

<h3>Albums</h3>

  <table>
    <tr>
      <th>Title</th>
      <th>Edit</th>
      <th>Delete</th>
      <th>Add Track</th>
    </tr>

    <% @band.albums.each do |album| %>
      <tr>
        <td><a href="<%= album_url(album) %>"><%= album.title %></a></td>

        <td><%= button_to "Edit Album", edit_album_url(album.id), method: :get %></td>

        <td>
          <form action="<%= album_url(album) %>" method="post">
            <input type="hidden" name="_method" value="delete">
            <%= button_to "Delete Album", album_url(album), method: :post %>
          </form>
        </td>

        <td>
          <form action="<%= new_track_url %>" method="get">
            <input type="hidden" name="track[album_id]" value="<%= album.id %>">
          <button>Add Track</button>
          </form>
        </td>

      </tr>
    <% end %>
  </table>